name: Publish
on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
  push:
    branches:
      - "main"

concurrency: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full Git history is fetched

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm install
      - run: npm install -g nx  # Install Nx globally if needed

      # Run Changesets to manage versioning and publishing
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # Nx release process
          publish: |
            nx run-many --target=build --all --exclude=test-app && \
            npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
